from PySide2 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.WindowModal)
        Dialog.resize(368, 507)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMaximumSize(QtCore.QSize(380, 600))
        Dialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lb_display = QtWidgets.QLabel(Dialog)
        self.lb_display.setMinimumSize(QtCore.QSize(0, 60))
        self.lb_display.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lb_display.setFont(font)
        self.lb_display.setStyleSheet("Background: white")
        self.lb_display.setText("")
        self.lb_display.setWordWrap(True)
        self.lb_display.setObjectName("lb_display")
        self.verticalLayout.addWidget(self.lb_display)
        self.lb_error = QtWidgets.QLabel(Dialog)
        self.lb_error.setStyleSheet("color: red")
        self.lb_error.setText("")
        self.lb_error.setWordWrap(True)
        self.lb_error.setObjectName("lb_error")
        self.verticalLayout.addWidget(self.lb_error)
        self.sa_vars = QtWidgets.QScrollArea(Dialog)
        self.sa_vars.setWidgetResizable(True)
        self.sa_vars.setObjectName("sa_vars")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 348, 69))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gl_vars = QtWidgets.QGridLayout()
        self.gl_vars.setObjectName("gl_vars")
        self.verticalLayout_2.addLayout(self.gl_vars)
        self.sa_vars.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.sa_vars)
        self.gl_funs = QtWidgets.QGridLayout()
        self.gl_funs.setObjectName("gl_funs")
        self.verticalLayout.addLayout(self.gl_funs)
        self.gl_nums = QtWidgets.QGridLayout()
        self.gl_nums.setObjectName("gl_nums")
        self.verticalLayout.addLayout(self.gl_nums)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout.setStretch(3, 1)
        self.verticalLayout.setStretch(4, 4)
        self.verticalLayout.setStretch(5, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))

